"""Scan policy for strict raw input vs. Scrubsmith-generated output."""

from __future__ import annotations

from enum import StrEnum


class ScanMode(StrEnum):
    """Controls how scan findings are interpreted."""

    STRICT = "strict"
    """Scan raw or untrusted input; detectors apply without synthetic allowances."""

    SCRUBSMITH_OUTPUT = "scrubsmith_output"
    """
    Scan output explicitly declared as previously generated by Scrubsmith.

    Recognizes well-defined Scrubsmith synthetic namespaces by format. This is
    weaker than the in-process dynamic allowlist used during sanitization.
    """
